-- MySQL Script generated by MySQL Workbench
-- Thu Dec 26 13:44:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `dno` INT NOT NULL AUTO_INCREMENT,
  `dname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `ssn` INT NOT NULL AUTO_INCREMENT,
  `sname` VARCHAR(45) NOT NULL,
  `grade` VARCHAR(45) NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `Department_dno` INT NOT NULL,
  PRIMARY KEY (`ssn`),
  INDEX `fk_Student_Department_idx` (`Department_dno` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Department`
    FOREIGN KEY (`Department_dno`)
    REFERENCES `mydb`.`Department` (`dno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `ssn` INT NOT NULL AUTO_INCREMENT,
  `pname` VARCHAR(45) NULL,
  `d_dno` INT NOT NULL,
  PRIMARY KEY (`ssn`),
  INDEX `fk_Professor_Department1_idx` (`d_dno` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Department1`
    FOREIGN KEY (`d_dno`)
    REFERENCES `mydb`.`Department` (`dno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
  `cno` INT NOT NULL AUTO_INCREMENT,
  `cname` VARCHAR(45) NOT NULL,
  `credit` INT NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`cno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Take`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Take` (
  `c_cno` INT NOT NULL,
  `s_ssn` INT NOT NULL,
  PRIMARY KEY (`c_cno`, `s_ssn`),
  INDEX `fk_Class_has_Student_Student1_idx` (`s_ssn` ASC) VISIBLE,
  INDEX `fk_Class_has_Student_Class1_idx` (`c_cno` ASC) VISIBLE,
  CONSTRAINT `fk_Class_has_Student_Class1`
    FOREIGN KEY (`c_cno`)
    REFERENCES `mydb`.`Class` (`cno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_has_Student_Student1`
    FOREIGN KEY (`s_ssn`)
    REFERENCES `mydb`.`Student` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Give`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Give` (
  `c_cno` INT NOT NULL,
  `p_ssn` INT NOT NULL,
  PRIMARY KEY (`c_cno`, `p_ssn`),
  INDEX `fk_Class_has_Professor_Professor1_idx` (`p_ssn` ASC) VISIBLE,
  INDEX `fk_Class_has_Professor_Class1_idx` (`c_cno` ASC) VISIBLE,
  CONSTRAINT `fk_Class_has_Professor_Class1`
    FOREIGN KEY (`c_cno`)
    REFERENCES `mydb`.`Class` (`cno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_has_Professor_Professor1`
    FOREIGN KEY (`p_ssn`)
    REFERENCES `mydb`.`Professor` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
